name = "cloud-mail"
main = "src/index.js"
compatibility_date = "2025-06-04"
keep_vars = true

[observability]
enabled = true

[[d1_databases]]
binding = "db"
database_name = "cloud-mail"
database_id = "78e55ee9-3179-4007-aa4e-911d63664bab"

[[kv_namespaces]]
binding = "kv"
id = "fde77a6131894723b5295f0f51393f11"

[ai]
binding = "ai"

[assets]
binding = "assets"
directory = "./dist"
not_found_handling = "single-page-application"
run_worker_first = true

[triggers]
crons = ["0 * * * *"]

[vars]
domain = ["freshai.eu.cc"]
admin = "admin@freshai.eu.cc"
jwt_secret = "fma8k2Qx7vL3pR9tW5yB1nC4zA6sD0gH2"

[build]
command = "pnpm --prefix ../mail-vue install && pnpm --prefix ../mail-vue run build"
